version: "3.9"

services:
  app:
    #build from current directory pickup dockerfile
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      #volume mapping from app directory (local directory)to app directory in container
      #make a change in source code and see the change reflected in container (for development)
      #- ./data/web:/vol/web maps vol/web inside docker to data/web inside container
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    



